### ISSUE TITLE
Trying to editing the converted forms causes fatal error with jet form builder

### ISSUE THREAD

**Issue by Imageburst** [Crocoblock/jet-form-builder-converter#1]
Hi, when trying to edit the converted forms it results in a fatal error. Please try this with newly converted forms from jet engine forms.

**Comment by girafffee** [comment]
Hi @Imageburst 
Could you share your form? You need to export it and add it here
![image](https://user-images.githubusercontent.com/46720998/204496172-27e282d4-dc40-4199-8b30-f5ddbe2bb237.png)

**Comment by CaporalF** [comment]
Having the same issue with the form created by the JetEngine Skin Manager preset ...
`TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Function.isEmptyObject (webpack-internal:///./package/tools.js:52:53)
    at eval (webpack-internal:///./editor/plugins/messages/render.js:42:20)
    at mountState (https://c0.wp.com/c/6.1.1/wp-includes/js/dist/vendor/react-dom.js:15656:22)
    at Object.useState (https://c0.wp.com/c/6.1.1/wp-includes/js/dist/vendor/react-dom.js:16278:18)
    at useState (https://c0.wp.com/c/6.1.1/wp-includes/js/dist/vendor/react.js:1533:23)
    at PluginMessages (webpack-internal:///./editor/plugins/messages/render.js:40:19)
    at renderWithHooks (https://c0.wp.com/c/6.1.1/wp-includes/js/dist/vendor/react-dom.js:15015:20)
    at updateFunctionComponent (https://c0.wp.com/c/6.1.1/wp-includes/js/dist/vendor/react-dom.js:17386:22)
    at mountLazyComponent (https://c0.wp.com/c/6.1.1/wp-includes/js/dist/vendor/react-dom.js:17707:19)`

Here is the form json:
`







`
